---
- hosts: all
  roles:
   - enablerdp
   - base

- hosts: sql
  roles:
   - sql

- hosts: all
  gather_facts: no
  tasks:
    - name: Install Windows updates
      win_updates:
         category_names:
            - SecurityUpdates
            - CriticalUpdates
            - UpdateRollups
            - DefinitionUpdates
            - Updates
         reboot: yes
         reboot_timeout: 3600
      register: win_update
      when: apply_win_updates == true
    - name: Reboot if updates require
      win_reboot:
      when: win_update.changed